# Generated by Django 5.2.8 on 2026-04-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surpluslisting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='surpluslisting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
