# Generated by Django 5.2.8 on 2026-05-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_airecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='airecommendation',
            name='leftover_potential',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='servings',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='servings_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
